version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

  chatbot:
    image: ghcr.io/ivanfioravanti/chatbot-ollama:main
    container_name: chatbot
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Use service name to talk between containers
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama-data:
